name: Build, Push, and Deploy User Service

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    name: Build, Push, and Deploy
    runs-on: ubuntu-latest

    env:
      AZURE_RG: finzen-rg
      ACR_SERVER: finzenacr.azurecr.io
      CA_NAME: finzen-api-users
      IMAGE_REPO: api-users

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and Package with Maven
        run: mvn clean package

      - name: 1. Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 2. ACR Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_SERVER }}
          username: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
          password: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}

      - name: 3. Docker Build
        run: docker build -t ${{ env.ACR_SERVER }}/${{ env.IMAGE_REPO }}:latest .

      - name: 4. Docker Push
        run: docker push ${{ env.ACR_SERVER }}/${{ env.IMAGE_REPO }}:latest

      - name: 5. Deploy/Update Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
          containerAppName: ${{ env.CA_NAME }}
          resourceGroup: ${{ env.AZURE_RG }}
          imageToDeploy: ${{ env.ACR_SERVER }}/${{ env.IMAGE_REPO }}:latest

      - name: Deployment Success
        run: echo "Microservicio de Ususarios desplegado exitosamente."